export const projects = [
  {
    id: '0',
    title: 'project-3-title',
    description: 'project-3-description',
    tools: [
      'Next.js',
      'Hardhat',
      'Ethers.js',
      'The Graph',
      'Wagmi',
      'Rainbow Kit',
      'TailwindCSS',
      'Toastify',
      'Multi-chains',
    ],
    imageURI: '/images/projects/smartvote-project.png',
    alt: 'SmartVote - Nicolas Milliard',
    githubURI: 'https://github.com/NicolasMilliard/SmartVote',
    projectURI: 'https://my-smartvote.vercel.app/',
    casestudyURI: 'smartvote',
  },
  {
    id: '1',
    title: 'project-1-title',
    description: 'project-1-description',
    tools: ['Next.js', 'Hardhat', 'Ethers.js', 'Wagmi', 'Rainbow Kit', 'TailwindCSS', 'Toastify'],
    imageURI: '/images/projects/kopo-project.png',
    alt: 'Kopo - Nicolas Milliard',
    githubURI: 'https://github.com/NicolasMilliard/kopo',
    projectURI: 'https://kopo.vercel.app/',
    casestudyURI: '',
  },
  {
    id: '2',
    title: 'project-2-title',
    description: 'project-2-description',
    tools: ['React JS', 'Hardhat', 'Ethers.js', 'TailwindCSS', 'Toastify'],
    imageURI: '/images/projects/chainboard-project.png',
    alt: 'Chainboard - Nicolas Milliard',
    githubURI: 'https://github.com/NicolasMilliard/chainboard',
    projectURI: 'https://chainboard.vercel.app/',
    casestudyURI: '',
  },
  {
    id: '3',
    title: 'Insert Dentaire',
    description:
      "Cette application permet aux dentistes de commander des inserts dentaires selon la marque, le modèle et l'utilisation. Elle est syncrhonisée avec le site internet et permet le suivi de sa commande en temps réel.",
    tools: ['React Native', 'API Chronopost', 'API Stripe'],
    imageURI: '/images/projects/chainboard-project.png',
    alt: 'Insert Dentaire - Nicolas Milliard',
    githubURI: '',
    projectURI: '',
    casestudyURI: '',
  },
];
